name: Generate token lists

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run generation'
        type: environment
        default: Test
        required: true
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run generation'
        type: string
        required: true
        default: 'Test'

jobs:
  install:
    name: 'Install'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check cache for "node_modules"
        id: cache
        uses: martijnhols/actions-cache/check@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Save "node_modules" to cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: martijnhols/actions-cache/save@v3
        with:
          path: '**/node_modules'
          key: ${{ steps.cache.outputs.primary-key }}

  generate-token-lists:
    name: 'Generate'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [install]
    permissions:
      id-token: write # need this for OIDC
      contents: read # This is required for actions/checkout@v2
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        commands:
          - name: Arb1 FullList
            path: [ArbTokenLists/arbed_full.json]
            version: false
            command: yarn fullList --l2NetworkID 42161 --newArbifiedList ./src/ArbTokenLists/arbed_full.json --skipValidation --ignorePreviousList

          - name: Arb1 Arbify Uniswap
            path: |
              [
                ArbTokenLists/arbed_uniswap_labs.json
                ArbTokenLists/arbed_uniswap_labs_default.json
              ]
            version: true
            command: yarn arbify --l2NetworkID 42161 --prevArbifiedList https://tokenlist.arbitrum.io/ArbTokenLists/arbed_uniswap_labs.json --tokenList https://tokens.uniswap.org --newArbifiedList ./src/ArbTokenLists/arbed_uniswap_labs.json && cp ./src/ArbTokenLists/arbed_uniswap_labs.json ./src/ArbTokenLists/arbed_uniswap_labs_default.json

          - name: Arb1 Arbify Gemini
            path: [ArbTokenLists/arbed_gemini_token_list.json]
            version: true
            command: yarn arbify --l2NetworkID 42161 --prevArbifiedList https://tokenlist.arbitrum.io/ArbTokenLists/arbed_gemini_token_list.json --tokenList https://www.gemini.com/uniswap/manifest.json --newArbifiedList ./src/ArbTokenLists/arbed_gemini_token_list.json

          - name: Arb1 Arbify CMC
            path: [ArbTokenLists/arbed_coinmarketcap.json]
            version: true
            command: yarn arbify --l2NetworkID 42161 --prevArbifiedList https://tokenlist.arbitrum.io/ArbTokenLists/arbed_coinmarketcap.json --tokenList https://api.coinmarketcap.com/data-api/v3/uniswap/all.json --newArbifiedList ./src/ArbTokenLists/arbed_coinmarketcap.json

          - name: Arb1 Update Whitelist
            path: [ArbTokenLists/arbed_arb_whitelist_era.json]
            version: true
            command: yarn update --l2NetworkID 42161 --prevArbifiedList https://tokenlist.arbitrum.io/ArbTokenLists/arbed_arb_whitelist_era.json --tokenList https://tokenlist.arbitrum.io/ArbTokenLists/arbed_arb_whitelist_era.json --includeOldDataFields true --newArbifiedList ./src/ArbTokenLists/arbed_arb_whitelist_era.json

          - name: ArbNova Arbify Uniswap
            path: |
              [
                ArbTokenLists/42170_arbed_uniswap_labs.json
                ArbTokenLists/42170_arbed_uniswap_labs_default.json
              ]
            version: true
            command: yarn arbify --l2NetworkID 42170 --prevArbifiedList https://tokenlist.arbitrum.io/ArbTokenLists/42170_arbed_uniswap_labs_default.json --newArbifiedList ./src/ArbTokenLists/42170_arbed_uniswap_labs.json --tokenList https://tokens.uniswap.org && cp ./src/ArbTokenLists/42170_arbed_uniswap_labs.json ./src/ArbTokenLists/42170_arbed_uniswap_labs_default.json

          - name: ArbNova Arbify Gemini
            path: [ArbTokenLists/42170_arbed_gemini_token_list.json]
            version: true
            command: yarn arbify --l2NetworkID 42170 --prevArbifiedList https://tokenlist.arbitrum.io/ArbTokenLists/42170_arbed_gemini_token_list.json  --tokenList https://www.gemini.com/uniswap/manifest.json --newArbifiedList ./src/ArbTokenLists/42170_arbed_gemini_token_list.json

          - name: ArbNova Arbify CMC
            path: [ArbTokenLists/42170_arbed_coinmarketcap.json]
            version: true
            command: yarn arbify --l2NetworkID 42170 --prevArbifiedList https://tokenlist.arbitrum.io/ArbTokenLists/42170_arbed_coinmarketcap.json --tokenList https://api.coinmarketcap.com/data-api/v3/uniswap/all.json --newArbifiedList ./src/ArbTokenLists/42170_arbed_coinmarketcap.json

          - name: ArbGoerli Arbify CMC
            path: [ArbTokenLists/421613_arbed_coinmarketcap.json]
            version: true
            command: yarn arbify --l2NetworkID 421613 --prevArbifiedList https://tokenlist.arbitrum.io/ArbTokenLists/421613_arbed_coinmarketcap.json --tokenList https://api.coinmarketcap.com/data-api/v3/uniswap/all.json --newArbifiedList ./src/ArbTokenLists/421613_arbed_coinmarketcap.json

          - name: ArbGoerli FullList
            path: [ArbTokenLists/421613_arbed_full.json]
            version: false
            command: yarn fullList --l2NetworkID 421613 --newArbifiedList ./src/ArbTokenLists/421613_arbed_full.json --skipValidation --ignorePreviousList
    env:
      INFURA_KEY: '${{ secrets.INFURA_KEY }}'
      MAINNET_RPC: 'https://mainnet.infura.io/v3/${{ secrets.INFURA_KEY }}'
      GOERLI_RPC: 'https://goerli.infura.io/v3/${{ secrets.INFURA_KEY }}'

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/restore-cache

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: 'us-west-2'
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ${{ matrix.commands.name }}
        if: success()
        run: ${{ matrix.commands.command }}

      - name: Get online version
        id: onlineVersion
        if: ${{ matrix.commands.version == true && matrix.commands.version == true  }}
        run: |
          version=$(curl https://tokenlist.arbitrum.io/${{ matrix.commands.path[0] }} | jq .version[] | awk 'NR > 1 { printf(".") } {printf "%s",$0}')
          echo "onlineVersion=$version" >> $GITHUB_OUTPUT

      - name: Get new version
        id: newVersion
        if: ${{ matrix.commands.version == true && matrix.commands.version == true }}
        run: |
          version=$(cat ./src/${{ matrix.commands.path[0] }} | jq .version[] | awk 'NR > 1 { printf(".") } {printf "%s",$0}')
          echo "newVersion=$version" >> $GITHUB_OUTPUT

      - name: Backup (Test folder)
        if: ${{ inputs.environment == 'Test' && matrix.commands.version == true }}
        run: |
          paths=(${{ join(matrix.commands.path, ', ') }})
          for path in ${paths[*]}
          do
            aws s3 cp s3://${{ secrets.AWS_BUCKET }}/TestFolder/$path s3://${{ secrets.AWS_BUCKET }}/TestFolder/${{ steps.onlineVersion.outputs.onlineVersion }}/
          done

      - name: Deploy (Test folder)
        if: ${{ inputs.environment == 'Test' }}
        run: aws s3 sync ./src/ s3://${{ secrets.AWS_BUCKET }}/TestFolder --exclude "*" --include "FullList/*.json" --include "ArbTokenLists/*.json"

      # - name: Backup
      #   if: ${{ inputs.environment == 'CI' && matrix.commands.version == true }}
      #   run: aws s3 cp s3://${{ secrets.AWS_BUCKET }}/TestFolder/${{ matrix.commands.path[0] }} s3://${{ secrets.AWS_BUCKET }}/TestFolder/${{ steps.onlineVersion.outputs.onlineVersion }}/

      - name: Deploy
        if: ${{ inputs.environment == 'CI' }}
        run: aws s3 sync ./src/ s3://${{ secrets.AWS_BUCKET }} --exclude "*" --include "FullList/*.json" --include "ArbTokenLists/*.json" --acl "public-read"

  error-alerts:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [install, generate-token-lists]
    # Run this job if any of the job in needs array failed
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Post errors to Slack channel
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Token list generation failed"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
